# Generated by Django 5.2.9 on 2025-12-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0002_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='name',
        ),
        migrations.AddField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('2XL', '2XL'), ('3XL', '3XL')], default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsize',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
