# Generated by Django 5.2.9 on 2025-12-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0003_remove_productsize_dimensions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='sold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
