# Generated by Django 5.2.9 on 2025-12-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0004_rename_stock_product_sold_remove_product_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('children', 'Children')], max_length=50),
        ),
    ]
