# Generated by Django 5.2.9 on 2025-12-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('gray', 'Gray'), ('navy', 'Navy Blue'), ('red', 'Red'), ('maroon', 'Maroon'), ('green', 'Green'), ('olive', 'Olive'), ('brown', 'Brown'), ('beige', 'Beige'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('coral', 'Coral'), ('sky_blue', 'Sky Blue'), ('mint', 'Mint'), ('peach', 'Peach'), ('mustard', 'Mustard'), ('rust', 'Rust')], help_text='Optional: Color of the product image', max_length=20, null=True),
        ),
    ]
