# Generated by Django 5.2.9 on 2025-12-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0006_productimage_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='color',
        ),
        migrations.AddField(
            model_name='productimage',
            name='color_choice',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('gray', 'Gray'), ('navy', 'Navy Blue'), ('red', 'Red'), ('maroon', 'Maroon'), ('green', 'Green'), ('olive', 'Olive'), ('brown', 'Brown'), ('beige', 'Beige'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('coral', 'Coral'), ('sky_blue', 'Sky Blue'), ('mint', 'Mint'), ('peach', 'Peach'), ('mustard', 'Mustard'), ('rust', 'Rust')], max_length=20, null=True, verbose_name='Select a color'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='custom_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Or enter custom color'),
        ),
    ]
