# Generated by Django 5.2.9 on 2025-12-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0008_productimage_size_productimage_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Pahiran', max_length=50),
        ),
    ]
