# Generated by Django 5.2.9 on 2025-12-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0009_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default='Pahiran', max_length=50),
        ),
    ]
