# Generated by Django 5.2.9 on 2025-12-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0010_product_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'XXL')], max_length=5, null=True, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Number of items available for this color/size', verbose_name='Stock Quantity'),
        ),
    ]
