# Generated by Django 5.2.9 on 2025-12-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='app_name',
        ),
    ]
